/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConstructorCall */

#ifndef _Included_ConstructorCall
#define _Included_ConstructorCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ConstructorCall
 * Method:    newString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ConstructorCall_newString
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
